project_id = "kluouelvtquksmudgisy"

[functions.ai-search]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.meo-login]
verify_jwt = false

[functions.meo-api-test]
verify_jwt = false
